### ISSUE TITLE
Failure on newman run with Incorrect Request. [Field 'startTime' shouldn't be null.]

### ISSUE THREAD

**Issue by mhariachyi-clgx** [reportportal/agent-js-postman#18]
preconditions:
`$ npm install -g newman-reporter-reportportal
+ newman-reporter-reportportal@0.0.18
added 24 packages from 20 contributors in 8.668s
`
the same for:
`$ npm install -g @reportportal/newman-reporter-reportportal
+ @reportportal/newman-reporter-reportportal@0.0.23
added 24 packages from 20 contributors in 13.517s`

run configuration:
`newman run ./AA_TEST_REPORT_PORTAL.postman_collection.json -e ./search.postman_environment.json -r reportportal  --reporter-reportportal-debug=true --reporter-reportportal-endpoint=https://xxx/api/v1 --reporter-reportportal-token=xxx --reporter-reportportal-launch=xxx --reporter-reportportal-project=yyy -x
`

the same for: 
`newman run ./AA_TEST_REPORT_PORTAL.postman_collection.json -e ./search.postman_environment.json -r @reportportal/reportportal --reporter-@reportportal/reportportal-debug=true --reporter-@reportportal/reportportal-endpoint=https://xxx.com/api/v1 --reporter-@reportportal/reportportal-token=xxx --reporter-@reportportal/reportportal-launch=xxx --reporter-@reportportal/reportportal-project=yyy -x
`

error message:
`Error: Request failed with status code 400: {"error_code":4001,"message":"Incorrect Request. [Field 'startTime' shouldn't be null.] "}
    at C:\Users\xxx\AppData\Roaming\nvm\v13.12.0\node_modules\newman-reporter-reportportal\node_modules\reportportal-client\lib\rest.js:27:23    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

**Comment by DzmitryHumianiuk** [comment]
@mhariachyi-clgx newman agent was not updated yet for RPv5.

**Comment by mhariachyi-clgx** [comment]
@DzmitryHumianiuk do you have plans for this update for the nearest future?

**Comment by DzmitryHumianiuk** [comment]
@mhariachyi-clgx yes,
but no any exact date.

stay tuned.

**Comment by AmsterGet** [comment]
Hi!
This issue will be resolved in a new version of the agent 5.0.0, which will be released and published in the `@reportportal/agent-js-postman` package.

**Comment by wazzaarvind** [comment]
@DzmitryHumianiuk  @AmsterGet Having the same issue. Is there any possible way to downgrade the agent version and get this working for newman? Please suggest if there are any other possible workarounds as well.

**Comment by AmsterGet** [comment]
Hi @wazzaarvind !
At the moment, since the new version of the agent has not been published yet, I can suggest to use the latest changes from the [`develop`] (https://github.com/reportportal/agent-js-postman/tree/develop) branch, but note that there is an unreleased version here that is subject to change.

**Comment by wazzaarvind** [comment]
Thanks for the response @AmsterGet, do we have any estimate on when this will be released?

**Comment by wazzaarvind** [comment]
We are using the version API Service: 4.3.4 of reportportal by the way, this is where I am trying to post the data. Not sure if that makes a difference though, or gives us any other options. Thank you.

**Comment by wazzaarvind** [comment]
> Hi @wazzaarvind !
> At the moment, since the new version of the agent has not been published yet, I can suggest to use the latest changes from the [`develop`] (https://github.com/reportportal/agent-js-postman/tree/develop) branch, but note that there is an unreleased version here that is subject to change.

@AmsterGet I did pull the package from the develop branch and it still gives me the same error.
