### ISSUE TITLE
Wrong test result publishing when Data File is used

### ISSUE THREAD

**Issue by vladislav-yevtushenko** [reportportal/agent-js-postman#23]
I run the postman collection using newman and reporter - "@reportportal/newman-reporter-reportportal": "0.0.23"

I have a data file with an 11 iteration record.
When I launch my collection I see an expected output in the Newman console but the report portal shows 11 duplicated suites.

It seems that the latest test suite result is copied to everywhere (including response body).
I expect to see this kind of result
![expected](https://user-images.githubusercontent.com/2672964/89509725-7c41d200-d7f1-11ea-9d97-3e642b26a4a2.png)

But in all test suites, I see only this one (which is actually related to 3 last cases)
![actual](https://user-images.githubusercontent.com/2672964/89509086-a941b500-d7f0-11ea-89c4-6242b90b5336.png)

**Comment by acer2004** [comment]
I have this problem as well.
