### ISSUE TITLE
Unable to see launches from newman run

### ISSUE THREAD

**Issue by pravinupganlawar** [reportportal/agent-js-postman#32]
Hi Team,
I am unable to see launches from newman run. However i can see  test item start/Success/Finish as well with save log on cli.
```
Start launch 12tzmgrckl6ezcht
Start test item 12tzmgrckl6ezci3
Start test item 12tzmgrckl6ezd4g
Start test item 12tzmgrckl6ezdga
Start test item 12tzmgrckl6ezdtk
Start test item 12tzmgrckl6eze64
Success start item 12tzmgrckl6ezci3
```

Could you please help me how can i see launches in report portal ? 

`
D:\Postman> newman run .\InternationalPaymentInitiationcollection.json --insecure --reporters @reportportal/reportportal --reporter-@reportportal/reportportal-debug=true --reporter-@reportportal/reportportal-endpoint=http://10.192
.XX.1XX:8080 --reporter-@reportportal/reportportal-token=167ebff4-276f-47ba-bd6f-bxxxx92544075 --reporter-@reportportal/reportportal-launch=POSTMAN_TEST_PRAVIN --reporter-@reportportal/reportportal-project=test-automation -x 
`
```
Start launch 12tzmgrckl6ezcht
Start test item 12tzmgrckl6ezci3
Start test item 12tzmgrckl6ezd4g
Start test item 12tzmgrckl6ezdga
Start test item 12tzmgrckl6ezdtk
Start test item 12tzmgrckl6eze64
Success start item 12tzmgrckl6ezci3
```

**Comment by deepaleekhare31** [comment]
@avarabyeu or @DzmitryHumianiuk Can you please help?

**Comment by DzmitryHumianiuk** [comment]
@deepaleekhare31 question is right to the point )
@KatsiarynaTatarynovich rework of Postman (Newman) integration right in current sprint, thus it will be available pretty soon.

**Comment by pravinupganlawar** [comment]
@DzmitryHumianiuk @KatsiarynaTatarynovich - Any updates on Postman (Newman) integration with Report Portal ? When we can expect to be available ?

**Comment by DzmitryHumianiuk** [comment]
@AmsterGet wasn't it released already?

**Comment by AmsterGet** [comment]
@pravinupganlawar Hello!
We recently released a new package with version 5.0.0 ([npm](https://www.npmjs.com/package/@reportportal/newman-reporter-agent-js-postman), github [packages](https://github.com/reportportal/agent-js-postman/packages/658832)), release [notes](https://github.com/reportportal/agent-js-postman/releases/tag/v5.0.0).

**Comment by DzmitryHumianiuk** [comment]
@pravinupganlawar please double check a new version and close issue if not relevant any more.
thank you.

**Comment by gregorygold** [comment]
I was able to find a work-around by removing the port 8080 from the URL

**Comment by AmsterGet** [comment]
Hi there!
I'll close this issue as there has been no reaction for a long time, but feel free to open it again if you have any questions related to the topic.
