### ISSUE TITLE
If the length of the Failures array is zero, the status is still set to failed

### ISSUE THREAD

**Issue by andrew-nodes** [reportportal/agent-js-postman#82]
I think there is a missing condition in the reporter.js file in the `onDone` function, because if the length of the Failures array is zero, the status is still set to failed.

Attaching the image with the problem on the top, and below is a possible solution.

File path `node_modules\@reportportal\newman-reporter-agent-js-postman\lib\reporter.js`

![Untitled-1](https://user-images.githubusercontent.com/88774213/174957518-3d4fb950-d409-42f5-8a8a-ee0709196132.png)

**Comment by AmsterGet** [comment]
Fixed.
Will be released in v5.0.3.
