### ISSUE TITLE
Report Portal showing incorrect Status as Failed though all Tests Passed

### ISSUE THREAD

**Issue by itsram113** [reportportal/agent-js-postman#89]
Report Portal showing the Status as FAIL though all my Tests were Passed which are executed by Newman.

Anyone faced similar issue and appreciate your help on this.

![image](https://user-images.githubusercontent.com/124382878/216654239-2786ca27-0c99-4512-a0d3-3fc6c58a2531.png)

**Comment by AmsterGet** [comment]
Hello @itsram113 !
Fixed in version [5.0.3](https://github.com/reportportal/agent-js-postman/releases/tag/v5.0.3).
