### ISSUE TITLE
Subfolders missing in the Report Portal hierarchy

### ISSUE THREAD

**Issue by vinnus8660** [reportportal/agent-js-postman#92]
Hi Team,

Integration of Postman Newman with report portal is successful with this package, but has an issue with the hierarchy.

My collections are in the below structure:

<img width="253" alt="image" src="https://user-images.githubusercontent.com/74465848/236354626-a52e1d3c-8e13-4bca-a32d-565767e1a657.png">

### **Expected hierarchy in Report Portal after Integration:**

Report Portal Launch name with the exact structure of collection under it.

<img width="234" alt="image" src="https://user-images.githubusercontent.com/74465848/236355023-b49438fd-8b52-4774-8154-b4875fba187f.png">

### **Actual hierarchy what we are seeing after Integration:**

Report Portal Launch name followed by collection name and all the tests from subfolders directly listed under it.

<img width="235" alt="image" src="https://user-images.githubusercontent.com/74465848/236355358-166f2119-07bb-4444-856a-e5dabea05493.png">

Hi @AmsterGet @chivekrodis Can you please provide your inputs on this? Is this a bug or am I missing something here?

**Comment by AmsterGet** [comment]
Hello @vinnus8660 !
For now, this behavior is by design of the agent.
This is a valuable point to consider for future implementation and has already been taken into account in our roadmap.
Since there is no ETA at the moment, any contribution is welcome.

**Comment by AmsterGet** [comment]
Looks like a duplicate with https://github.com/reportportal/agent-js-postman/issues/62
I suggest to keep updates in the issue above.
